apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: attendance-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PavanKrish2494/wanderblogg.git
    targetRevision: HEAD
    path: attendance-app-chart
    helm:
      releaseName: attendance-app-release
  destination:
    server: https://kubernetes.default.svc
    namespace: attendance-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
