apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.db.DB_PASSWORD | quote }}
  DB_USER: {{ .Values.db.DB_USER | quote }}